"""Generate ../mcbpc_table.go from data/table_mb_intra_raw.json — the combined MS-MPEG4 v3
per-MB INTRA coded-block-pattern VLC (64 patterns: chroma cb,cr x luma y0..y3). The JSON is
black-box derived by re/iframe_mcbpc.py (encoder-oracle: single-MB I-frames, cbp read from
decoded pixels with intra CBP prediction undone, codeword isolated by block-0 DC first-diff).
Key 'CC_YYYY' (cb cr _ y0 y1 y2 y3) -> codeword bits."""
import json, os
_RE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # re/
PKG = os.path.dirname(_RE)                                          # go-msmpeg4/
d = json.load(open(f"{_RE}/common/data/table_mb_intra_raw.json"))  # {"cb cr_y0y1y2y3": bits}
rows = []
for key, bits in d.items():
    cc, yyyy = key.split("_")
    cb, cr = int(cc[0]), int(cc[1])
    y0, y1, y2, y3 = (int(c) for c in yyyy)
    rows.append((len(bits), int(bits, 2), len(bits), cb, cr, y0, y1, y2, y3))
rows.sort()
go = "package msmpeg4\n\n"
go += "// Code generated by re/gen_mcbpc_go.py — DO NOT EDIT.\n"
go += "// Combined MS-MPEG4 v3 per-MB INTRA coded-block-pattern VLC (64 patterns), black-box\n"
go += "// reversed. Maps the per-MB prefix to chroma cbp (cb,cr) and luma cbp (y0..y3).\n"
go += "type mcbpcCode struct{ length, code, cb, cr, y0, y1, y2, y3 int }\n\n"
go += "var mcbpcVLC = []mcbpcCode{\n"
for _, code, ln, cb, cr, y0, y1, y2, y3 in rows:
    go += f"\t{{{ln}, 0b{code:0{ln}b}, {cb}, {cr}, {y0}, {y1}, {y2}, {y3}}},\n"
go += "}\n"
open(f"{PKG}/mcbpc_table.go", "w").write(go)
print(f"wrote mcbpc_table.go: {len(rows)} patterns")
