"""Generate go-msmpeg4/dc_table.go from the parsed DC VLC tables."""
import os
import json, textwrap

src = json.load(open("/tmp/dc_full.json"))

lines = [
    "// Code generated by re/gen_dc_go.py; DO NOT EDIT.",
    "",
    "package msmpeg4",
    "",
    "// dcMax is the escape sentinel: when the VLC returns dcMax, 8 more bits",
    "// follow for the actual level magnitude, then a sign bit.",
    "const dcMax = 119",
    "",
    "// dcTable maps VLC bit-strings to DC magnitudes (0..dcMax).",
    "type dcTable struct{ vlc map[string]int }",
    "",
    "// dcTables[dctIdx][isChroma] — dctIdx ∈ {0,1}, isChroma ∈ {0,1}.",
    "var dcTables [2][2]*dcTable",
    "",
    "func init() {",
]

for key, entries in sorted(src.items()):
    dct, ch = key.split(",")
    varname = f"dcRaw{dct}_{ch}"
    bits_list = [entries[str(m)] for m in range(120)]

    lines.append(f"\t{varname} := map[string]int{{")
    for mag, bits in enumerate(bits_list):
        lines.append(f'\t\t"{bits}": {mag},')
    lines.append("\t}")
    lines.append(f"\tdcTables[{dct}][{ch}] = &dcTable{{vlc: {varname}}}")
    lines.append("")

lines.append("}")

out = "\n".join(lines) + "\n"
open(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "dc_table.go"), "w").write(out)
print(f"Wrote dc_table.go ({len(lines)} lines, {len(out)} bytes)")
