#!/usr/bin/env python3
"""gen_dc_luma.py — derive the intra DC *luma* differential VLC of MS-MPEG4 v3
and emit dc_luma_table.go.

PROOF OF PROVENANCE. This is the script that produced go-msmpeg4's DC luma table.
It does NOT read ffmpeg source or any Microsoft binary. It works purely by:

  1. Encoding 256 solid 16x16 frames (luma value V = 0..255, chroma fixed 128)
     to DIV3 with the ffmpeg encoder used as a black box (see craft.sh).
  2. For each V, isolating block-0's DC codeword from the byte-padded frame by
     anchoring against the FIXED blocks-1..5 "TAIL" (pad-independent) and the
     true field boundary P=19 (= 7-bit picture header + 12-bit MCBPC|CBPY,
     found earlier via first-bit-difference between frames with different DC).
  3. Labelling each codeword's signed level by RANK around the L=0 code (`10`),
     cross-checked against the decoded-pixel oracle (dc_scaler=16 at q=8, so the
     flat reconstruction is 128 + 2*level).

Run:  re/craft.sh /tmp/msm_craft   # produces a{0..255}.bin   (or see below)
      python3 re/gen_dc_luma.py /tmp/msm_craft > dc_luma_table.go
"""
import os
import sys

P = 19  # header(7) + MCBPC|CBPY(12); block-0 DC starts here


def bits(path):
    with open(path, "rb") as f:
        return "".join(format(x, "08b") for x in f.read())


def main(d):
    # If the a{V}.bin frames are absent, synthesise them with craft.sh's recipe.
    if not os.path.exists(f"{d}/a128.bin"):
        for V in range(256):
            os.system(
                f'python3 -c "import sys;sys.stdout.buffer.write(bytes([{V}]*256+[128]*64+[128]*64))" > {d}/a{V}.yuv && '
                f"ffmpeg -y -v error -f rawvideo -pix_fmt yuv420p -s 16x16 -i {d}/a{V}.yuv "
                f"-c:v msmpeg4 -qscale:v 8 -frames:v 1 -vtag DIV3 {d}/a{V}.avi && "
                f"ffmpeg -y -v error -i {d}/a{V}.avi -map 0:v:0 -c copy -frames:v 1 -f data {d}/a{V}.bin"
            )

    tail = bits(f"{d}/a128.bin")[P + 2 :].rstrip("0")  # blocks 1..5 anchor

    def dccode(V):
        body = bits(f"{d}/a{V}.bin")[P:]
        for L in range(len(body) + 1):
            if body[L:].rstrip("0") == tail:
                return body[:L]
        return None

    c2v = {}
    for V in range(256):
        c = dccode(V)
        if c:
            c2v.setdefault(c, []).append(V)
    codes = sorted(c2v, key=lambda c: sum(c2v[c]) / len(c2v[c]))
    zi = codes.index(next(c for c in codes if 128 in c2v[c]))  # L=0 code

    out = sys.stdout
    out.write("package msmpeg4\n\n")
    out.write("// Code generated by re/gen_dc_luma.py — DO NOT EDIT.\n")
    out.write(
        "// Intra DC luma differential VLC for MS-MPEG4 v3, reverse-engineered by\n"
    )
    out.write("// black-box bitstream analysis (re/craft.sh) + decoded-pixel oracle.\n")
    out.write(
        "// {code length, code bits, signed DC level}; levels -64..+64; dc_scaler=2*q.\n"
    )
    out.write("var dcLumaVLC = []dcCode{\n")
    for i, c in enumerate(codes):
        out.write(f"\t{{{len(c)}, 0b{c}, {i - zi}}},\n")
    out.write("}\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/tmp/msm_craft")
