#!/usr/bin/env python3
"""gen_dc_chroma.py — derive the intra DC *chroma* differential VLC of MS-MPEG4
v3 and emit dc_chroma_table.go.

PROOF OF PROVENANCE (see gen_dc_luma.py). Same black-box method, for chroma.

Encode 256 solid frames varying only Cb (luma=128); **Cr is fixed at 200**, not
128, so that block-5 (the Cr block) is a fixed *non-zero* DC code and forms a
usable anchor — with Cr=128 its code is `00`+pad = all zeros, which a trailing-
zero strip would eat. Block-4 (Cb) DC starts at bit 27 = 7 (picture header)
+ 12 (MCBPC|CBPY) + 4*2 (four luma blocks, each DC(level 0)=`10`). Its codeword
is isolated by reconvergence with the fixed block-5 TAIL, then labelled by signed
rank around the Cb=128 (level-0) code.

Run:  python3 re/gen_dc_chroma.py /tmp/msm_craft > dc_chroma_table.go
"""
import os
import sys

P = 27


def bits(path):
    with open(path, "rb") as f:
        return "".join(format(x, "08b") for x in f.read())


def strip(s):  # drop up to 7 trailing zero pad bits
    k, t = 0, s
    while k < 7 and t.endswith("0"):
        t, k = t[:-1], k + 1
    return t


def main(d):
    if not os.path.exists(f"{d}/db128.bin"):
        for V in range(256):
            os.system(
                f'python3 -c "import sys;sys.stdout.buffer.write(bytes([128]*256+[{V}]*64+[200]*64))" > {d}/db{V}.yuv && '
                f"ffmpeg -y -v error -f rawvideo -pix_fmt yuv420p -s 16x16 -i {d}/db{V}.yuv "
                f"-c:v msmpeg4 -qscale:v 8 -frames:v 1 -vtag DIV3 {d}/db{V}.avi && "
                f"ffmpeg -y -v error -i {d}/db{V}.avi -map 0:v:0 -c copy -frames:v 1 -f data {d}/db{V}.bin"
            )

    # TAIL (block-5 Cr=200 code + nothing) = common suffix of two frames with
    # different block-4 (Cb).
    s128, s0 = strip(bits(f"{d}/db128.bin")), strip(bits(f"{d}/db0.bin"))
    n = 0
    while n < len(s128) and n < len(s0) and s128[-1 - n] == s0[-1 - n]:
        n += 1
    tail = s128[len(s128) - n :]

    def dccode(V):
        body = strip(bits(f"{d}/db{V}.bin"))[P:]
        return body[: len(body) - len(tail)] if body.endswith(tail) else None

    c2v = {}
    for V in range(256):
        c = dccode(V)
        if c is not None:
            c2v.setdefault(c, []).append(V)
    codes = sorted(c2v, key=lambda c: sum(c2v[c]) / len(c2v[c]))
    zi = codes.index(next(c for c in codes if 128 in c2v[c]))

    out = sys.stdout
    out.write("package msmpeg4\n\n")
    out.write("// Code generated by re/gen_dc_chroma.py — DO NOT EDIT.\n")
    out.write(
        "// Intra DC chroma differential VLC for MS-MPEG4 v3, reverse-engineered by\n"
    )
    out.write("// black-box bitstream analysis (re/craft.sh) + decoded-pixel oracle.\n")
    out.write("// {code length, code bits, signed DC level} (rank around level 0).\n")
    out.write("var dcChromaVLC = []dcCode{\n")
    for i, c in enumerate(codes):
        out.write(f"\t{{{len(c)}, 0b{c}, {i - zi}}},\n")
    out.write("}\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/tmp/msm_craft")
