"""Generate ../tcoef_table.go from the committed RL tables:
luma = data/rl_table2.json (= open ISO/IEC 14496-2 intra VLC, 102 codes),
chroma = data/rl_chroma.json (black-box reversed, 168 codes). Emits the two VLC
tables plus per-(last,run) max-level arrays used by the level-escape (ESC mode 1)."""
import json, os
_RE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # re/
DATA = os.path.join(_RE, "common", "data")
PKG = os.path.dirname(_RE)                                          # go-msmpeg4/
def load(fn):
    return {tuple(int(x) for x in k.split(",")): v for k, v in json.load(open(fn)).items()}
luma = load(f"{DATA}/rl_table2.json")
chroma = load(f"{DATA}/rl_chroma.json")
def entries(tbl):
    out = []
    for (run, level, last), bits in sorted(tbl.items()):
        out.append((run, level, last, len(bits), int(bits, 2)))
    return out
def maxlev(tbl):
    mx = [[0] * 64 for _ in range(2)]
    for (run, level, last), _ in tbl.items():
        if run < 64 and level > mx[last][run]:
            mx[last][run] = level
    return mx
def fmt_entries(name, es, comment):
    L = [f"// {comment}", f"var {name} = []tcoefCode{{"]
    for r, l, la, ln, c in es:
        L.append(f"\t{{{r}, {l}, {la}, {ln}, 0b{c:0{ln}b}}},")
    L.append("}")
    return "\n".join(L)
def fmt_maxlev(name, mx):
    rows = []
    for last in range(2):
        vals = ", ".join(str(v) for v in mx[last])
        rows.append(f"\t{{{vals}}},")
    return f"// {name}[last][run] = max coded level — added to the base level on ESC mode 1.\nvar {name} = [2][64]int{{\n" + "\n".join(rows) + "\n}"
go = "package msmpeg4\n\n"
go += "// Code generated by re/gen_tcoef_go.py — DO NOT EDIT.\n"
go += "// MS-MPEG4 v3 intra AC TCOEF tables. Luma = open ISO/IEC 14496-2 intra VLC\n"
go += "// (independently black-box-reversed, 102/102). Chroma = black-box-reversed (168/168).\n"
go += "// Each: {run, level, last, length, code}; the sign bit follows the codeword in-stream.\n\n"
go += "type tcoefCode struct{ run, level, last, length, code int }\n\n"
go += fmt_entries("tcoefLumaVLC", entries(luma), "luma intra (ISO/IEC 14496-2), 102 codes") + "\n\n"
go += fmt_entries("tcoefChromaVLC", entries(chroma), "chroma (black-box reversed), 168 codes") + "\n\n"
go += fmt_maxlev("maxlevLuma", maxlev(luma)) + "\n\n"
go += fmt_maxlev("maxlevChroma", maxlev(chroma)) + "\n"
open(f"{PKG}/tcoef_table.go", "w").write(go)
print(f"wrote tcoef_table.go: luma={len(luma)} chroma={len(chroma)} codes")
